### ISSUE TITLE
change command colour

### ISSUE THREAD

**Issue by binarymaker** [jhanikhilnath/bright_color_theme#1]
Thanks for the amazing theme. 

I would like to change the command colour grey to half white. I feel little difficult to read grey texts in code
how can I modify regarding this?

**Comment by jhanikhilnath** [comment]
Which color?? You mean the terminal color

If not then, attach screenshots of the thing you want to change

**Comment by binarymaker** [comment]
inside code editor
![grey](https://user-images.githubusercontent.com/45413608/103002755-80c71700-4555-11eb-85dc-8bad5b0ee3d7.png)


And hex decimal number shows in 2 different colour - 0x1 -> it shall be same colour

**Comment by jhanikhilnath** [comment]
Which language is this

**Comment by binarymaker** [comment]
C language. I using this in embedded programming

**Comment by jhanikhilnath** [comment]
I think I wont be able fix this as I do not know C and its terms.

I Am Sorry

I originally made this theme for Web Dev and Python, and it automatically got optimised for other languages.

**Comment by binarymaker** [comment]
thanks for your time.

no need to understand c language to make this fix. you may do in JSON settings

**Comment by jhanikhilnath** [comment]
I need to know the terms in C for me to be able to fix it
